Django_Blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from Django_Blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import BlogHome, BlogPostCreateView, BlogPostDeleteView, BlogPostDetailView, BlogPostUpdateView

app_name = 'posts'
urlpatterns = [
    path('', BlogHome.as_view(), name='home'),
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('<str:slug>/', BlogPostDetailView.as_view(), name='detail'),
    path('edit/<str:slug>/', BlogPostUpdateView.as_view(), name='edit'),
    path('delete/<str:slug>/', BlogPostDeleteView.as_view(), name='delete'),
]

posts/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse
# from django.contrib.auth import get_user_model
# Create your models here.

# User = get_user_model()
class BlogPost(models.Model):
    title = models.CharField(max_length=200, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Publie")
    content = models.TextField(blank=True, verbose_name="Contenu")
    thumbnail = models.ImageField(blank=True, upload_to="blogImage")
    
    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    @property
    def author_or_default(self):
        if self.author:
            return self.author.username
        return "Auteur non defini"
    
    def get_absolute_url(self):
        return reverse('posts:home',)

posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from posts.models import BlogPost
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# Create your views here.

class BlogHome(ListView):
    model = BlogPost
    context_object_name = 'posts'
    # template_name='posts/blogpostList.html'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published='True')
    
@method_decorator(login_required, name='dispatch')
class BlogPostCreateView(CreateView):
    model = BlogPost
    template_name = "posts/blogpost_create.html"
    fields = ['title', 'content']
    

class BlogPostUpdateView(UpdateView):
    model = BlogPost
    template_name = "posts/blogpost_edit.html"
    fields = ['title', 'content', 'published']
    

class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = "posts/blogpost_detail.html"
    context_object_name = 'post'
    

class BlogPostDeleteView(DeleteView):
    model = BlogPost
    template_name = "posts/blogpost_confirm_delete.html"
    success_url = reverse_lazy("posts:home")
    context_object_name = 'post'

posts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}

    {% endblock %}
    
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="">
        <a class="" href="{% url 'posts:home'%}">Home</a>
        {% if request.user.is_authenticated %}
            <a class="" href="{% url 'posts:create'%}">Ajouter</a>
        {% endif %}
    </nav>
 
    <section id="blog">
        {% block content %}
        {% endblock %}
    </section>
</body>
</html>

posts/templates/posts/blogpost_confirm_delete.html
{% extends "base.html" %}

{% block title %}
    <title>supprimer un article</title>
{% endblock %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer cet article {{ post.title}} ?</p>
        <input class="btn btn-delete" type="submit" value="Oui, supprimer">
    </form>
{% endblock content %}
    

posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
    <title>Ajouter un nouvel Article</title>
{% endblock %}


{% block content %}
    <h1>Ajouter un nouvel Article</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-submit" type="submit" value="Ajouter">
    </form>
{% endblock content %}
    

posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}


{% block title %}
<title>{{ post.title }}</title>
{% endblock title %}


{% block content %}
<article class="post-detail">
    <h1>{{ post.title }}</h1>
    <img src="{{ post.thumbnail.url }}" alt="" srcset="">
    <div class="">
        {{ post.content|linebreaks|safe }}
    </div>
</article>
{% endblock content %}

posts/templates/posts/blogpost_edit.html
{% extends 'base.html' %}


{% block title %}
    <title>Editer l'article</title>
{% endblock title %}
    

{% block content %} 
    <h1>Editer l'article</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-submit" type="submit">Editer</input>
    </form>
{% endblock content %}  
    

posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}

{% block title %}
<title>Bienvenu sur mon blog</title>
{% endblock %}

{% block content %}
<h1>Le blog des blogs</h1>
{% for post in posts %}
<article>
    <div class="post-title">
        <h2>{{ post.title }}</h2>
        {% if request.user.is_authenticated %}
        <div>
            <a class="" href="{% url 'posts:edit' slug=post.slug %}">Editer</a>
            <a class="" href="{% url 'posts:delete' slug=post.slug %}">Supprimer</a>
        </div>
        {% endif %}
    </div>
    <h5 class="post-author">
        Publié par <i>{{ post.author_or_default}}, </i> le {{ post.created_on|date }}
    </h5>
    <p class="post-excerpt">{{ post.content|safe|truncatewords:50 }}</p>
    <form action="{% url 'posts:detail' slug=post.slug %}">
        <input class="btn btn-submit" type="submit" value="Lire la suite">
    </form>
</article>
{% endfor %}

{% endblock %}